# Generated by Django 3.1.1 on 2020-10-05 05:07

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=author.models.AuthorProfileModel.get_author_image_path),
        ),
    ]
